### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by edukdt** [dnnsoftware/Dnn.Releases.Archive.7x#2] opened 2021-09-22 22:05 UTC
I'm trying to download DNN 7.4.2 and I'm getting the folowing error:

Cloning into 'C:\Users\...\Documents\GitHub\Dnn.Releases.Archive.7x'...
remote: Enumerating objects: 298, done.        
remote: Total 298 (delta 0), reused 0 (delta 0), pack-reused 298        
Receiving objects: 100% (298/298), 964.40 MiB | 25.50 MiB/s, done.
Resolving deltas: 100% (52/52), done.
Downloading 07.00.00 RC (Not for Production Use)/DotNetNuke_Community_7.0.0.1562_Install.zip (44 MB)
Error downloading object: 07.00.00 RC (Not for Production Use)/DotNetNuke_Community_7.0.0.1562_Install.zip (6f1cacd): Smudge error: Error downloading 07.00.00 RC (Not for Production Use)/DotNetNuke_Community_7.0.0.1562_Install.zip (6f1cacd9fc76beeafe81a48a376c36122c2cc9f185ffa7744d0f0789249b7675): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by david-poindexter** [comment] 2021-09-22 22:09
@edukdt to download DNN 7.4.2, you just need to...

* Go to https://github.com/dnnsoftware/Dnn.Releases.Archive.7x/tree/master/07.04.02
* Click on the appropriate package (Install, Upgrade, etc.)
* Click on the "Raw" icon.  (This will download the desired package.)

You don't want to close this repo - it is massive!  😉

**Comment by edukdt** [comment] 2021-09-22 22:12
I tried cloning the whole repo because download via Raw was resulting in a invalid file with 1kb size. 
Just tried it again and got the same error

**Comment by david-poindexter** [comment] 2021-09-22 22:13
Which package are you trying to download?

**Comment by edukdt** [comment] 2021-09-22 22:13
DNN_Platform_07.04.02_Upgrade.zip

**Comment by david-poindexter** [comment] 2021-09-22 22:15
@edukdt it works perfectly for me.  Here is a direct link:
https://github.com/dnnsoftware/Dnn.Releases.Archive.7x/raw/master/07.04.02/DNN_Platform_07.04.02_Upgrade.zip

If this doesn't work for you, you can also get it using [nvQuickSite](https://nvquicksite.com).  😉

**Comment by edukdt** [comment] 2021-09-22 22:21
I will try nvQuickSite.
I had no luck with the direct link and a co-worker also tried and had no sucess. The files are downloaded, but don't work.
As you can see in the screenshot the file have 1kb only. Have you tried opening the files on the desktop to unzip them?
https://imgur.com/a/is9PzUs

**Comment by david-poindexter** [comment] 2021-09-22 22:26
Well that is very interesting.  I am actually getting the same error with the file being only 1KB.  That is also what I am getting within nvQuickSite as well.

My guess is DNN Corp didn't pay their bill for LFS.  😭 

Tagging @ashishpd to see if he knows anything.

**Comment by david-poindexter** [comment] 2021-09-22 23:27
@edukdt in the meantime, if you are a brave soul, you can go to the CodePlex Archive and get it from there:  https://archive.codeplex.com/?p=dotnetnuke

**Comment by zyhfish** [comment] 2021-09-23 03:34
Hi @edukdt , can you please check whether this workaround works for you: http://www.jerrylsu.net/articles/2021/tools-Git-LFS-Bandwidth-Issue.html

**Comment by edukdt** [comment] 2021-09-23 12:49
> Hi @edukdt , can you please check whether this workaround works for you: http://www.jerrylsu.net/articles/2021/tools-Git-LFS-Bandwidth-Issue.html

Thanks, the work around worked for me and I was able to download the version.

**Comment by david-poindexter** [comment] 2021-09-23 21:23
Thanks for the workaround @zyhfish.  However, I'd like to keep this issue open so we can address the root cause.  This is a problem for EVERY file in ALL DNN Archive repositories.  I sent @ashishpd an email about this yesterday.  He replied and said he was going to look into it.  Hopefully, it was just an accounting oversight.  This is needed moving forward for sure!

**Comment by david-poindexter** [comment] 2021-11-06 13:59
@ashishpd do you happen to have an update on the account issue?  Thanks!

**Comment by zyhfish** [comment] 2021-12-03 02:42
Hi @edukdt , the issue has been fixed, please try to download the package by the suggestions from @david-poindexter as below:
Go to https://github.com/dnnsoftware/Dnn.Releases.Archive.7x/tree/master/07.04.02
Click on the appropriate package (Install, Upgrade, etc.)
Click on the "Raw" icon. (This will download the desired package.)

Thanks,
Ben

**Closed as completed** 2021-12-06 12:36 UTC
